-- MySQL Script generated by MySQL Workbench
-- 06/25/16 18:27:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matrix
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `matrix` ;

-- -----------------------------------------------------
-- Schema matrix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matrix` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `matrix` ;

-- -----------------------------------------------------
-- Table `matrix`.`Pontuacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Pontuacoes` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Pontuacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ds` VARCHAR(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`Palavras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Palavras` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Palavras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ds` VARCHAR(45) NOT NULL,
  `id_p` INT NOT NULL,
  PRIMARY KEY (`id`, `id_p`),
  INDEX `fk_Palavras_Pontuacoes1_idx` (`id_p` ASC),
  CONSTRAINT `fk_Palavras_Pontuacoes1`
    FOREIGN KEY (`id_p`)
    REFERENCES `matrix`.`Pontuacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`Frases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Frases` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Frases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qt` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `matrix`.`Frases_has_Palavras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Frases_has_Palavras` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Frases_has_Palavras` (
  `id` INT NOT NULL,
  `id_f` INT NOT NULL,
  `id_p` INT NOT NULL,
  PRIMARY KEY (`id`, `id_f`, `id_p`),
  INDEX `fk_Frases_has_Palavras_Palavras1_idx` (`id_p` ASC),
  INDEX `fk_Frases_has_Palavras_Frases_idx` (`id_f` ASC),
  CONSTRAINT `fk_Frases_has_Palavras_Frases`
    FOREIGN KEY (`id_f`)
    REFERENCES `matrix`.`Frases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Frases_has_Palavras_Palavras1`
    FOREIGN KEY (`id_p`)
    REFERENCES `matrix`.`Palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`sugestores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`sugestores` ;

CREATE TABLE IF NOT EXISTS `matrix`.`sugestores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qt_uso` INT NOT NULL DEFAULT 0,
  `qt_acerto` INT NOT NULL DEFAULT 0,
  `dt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`sugestores_has_sugestores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`sugestores_has_sugestores` ;

CREATE TABLE IF NOT EXISTS `matrix`.`sugestores_has_sugestores` (
  `id_s` INT NOT NULL,
  `id_s_pai` INT NOT NULL,
  PRIMARY KEY (`id_s`, `id_s_pai`),
  INDEX `fk_sugestores_has_sugestores_sugestores2_idx` (`id_s_pai` ASC),
  INDEX `fk_sugestores_has_sugestores_sugestores1_idx` (`id_s` ASC),
  CONSTRAINT `fk_sugestores_has_sugestores_sugestores1`
    FOREIGN KEY (`id_s`)
    REFERENCES `matrix`.`sugestores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sugestores_has_sugestores_sugestores2`
    FOREIGN KEY (`id_s_pai`)
    REFERENCES `matrix`.`sugestores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`tipos_estrutura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`tipos_estrutura` ;

CREATE TABLE IF NOT EXISTS `matrix`.`tipos_estrutura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ds` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`estruturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`estruturas` ;

CREATE TABLE IF NOT EXISTS `matrix`.`estruturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_t` INT NOT NULL,
  `ds` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estruturas_tipos_estrutura1_idx` (`id_t` ASC),
  CONSTRAINT `fk_estruturas_tipos_estrutura1`
    FOREIGN KEY (`id_t`)
    REFERENCES `matrix`.`tipos_estrutura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`sugestores_has_estruturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`sugestores_has_estruturas` ;

CREATE TABLE IF NOT EXISTS `matrix`.`sugestores_has_estruturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_s` INT NOT NULL,
  `id_e` INT NOT NULL,
  PRIMARY KEY (`id`, `id_s`, `id_e`),
  INDEX `fk_sugestores_has_estruturas_estruturas1_idx` (`id_e` ASC),
  INDEX `fk_sugestores_has_estruturas_sugestores1_idx` (`id_s` ASC),
  CONSTRAINT `fk_sugestores_has_estruturas_sugestores1`
    FOREIGN KEY (`id_s`)
    REFERENCES `matrix`.`sugestores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sugestores_has_estruturas_estruturas1`
    FOREIGN KEY (`id_e`)
    REFERENCES `matrix`.`estruturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`Datas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Datas` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Datas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`Textos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Textos` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Textos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`Textos_has_Datas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Textos_has_Datas` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Textos_has_Datas` (
  `id_t` INT NOT NULL,
  `id_d` INT NOT NULL,
  PRIMARY KEY (`id_t`, `id_d`),
  INDEX `fk_Textos_has_Datas_Datas1_idx` (`id_d` ASC),
  INDEX `fk_Textos_has_Datas_Textos1_idx` (`id_t` ASC),
  CONSTRAINT `fk_Textos_has_Datas_Textos1`
    FOREIGN KEY (`id_t`)
    REFERENCES `matrix`.`Textos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Textos_has_Datas_Datas1`
    FOREIGN KEY (`id_d`)
    REFERENCES `matrix`.`Datas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matrix`.`Textos_has_Frases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matrix`.`Textos_has_Frases` ;

CREATE TABLE IF NOT EXISTS `matrix`.`Textos_has_Frases` (
  `id` INT NOT NULL,
  `id_t` INT NOT NULL,
  `id_f` INT NOT NULL,
  PRIMARY KEY (`id`, `id_t`, `id_f`),
  INDEX `fk_Textos_has_Frases_Frases1_idx` (`id_f` ASC),
  INDEX `fk_Textos_has_Frases_Textos1_idx` (`id_t` ASC),
  CONSTRAINT `fk_Textos_has_Frases_Textos1`
    FOREIGN KEY (`id_t`)
    REFERENCES `matrix`.`Textos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Textos_has_Frases_Frases1`
    FOREIGN KEY (`id_f`)
    REFERENCES `matrix`.`Frases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
